baseURL = "https://www.stablemilkingstool.co.uk/"
languageCode = "en"
defaultContentLanguage = "en"
title = "A Very Stable Milking Stool"
theme = "stip"
ignoreErrors = ["error-disable-taxonomy"]
disableKinds = ["page", "section", "taxonomy"]

[Author]
    name = "A Very Stable Milking Stool"
    bio1 = "Feeding all The Mermaids."
    bio2 = "With all The Kebabs."

[params]
    [[redirects]]
        from = '/**'
        status = 404
        to = '/404.html'

    [[params.links]]
        iconset = "fab"
        icon = "bluesky"
        title = "Blue Sky"
        url = "https://bsky.app/profile/stablemilkingstool.co.uk"

    [[params.links]]
        iconset = "fab"
        icon = "x-twitter"
        title = "X"
        url = "https://twitter.com/MonkeyOfStool"

[[params.links]]
        icon = "youtube"
        title = "YouTube"
        url = "https://www.youtube.com/channel/UCapl-PQf15W4wiP3v6g9v8A"    

    [[params.links]]
        icon = "twitch"
        title = "Twitch"
        url = "https://www.twitch.tv/stable_milking_stool"   

    [[params.links]]
        icon = "discord"
        title = "Discord"
        url = "https://discord.gg/NDRWjgZkqp"

    [[params.links]]
        icon = "steam"
        title = "Steam"
        url = "https://steamcommunity.com/id/StableMilkingStool/"

    [[params.links]]
        icon = "paypal"
        title = "PayPal"
        url = "https://paypal.me/JonesHoward"
    
    [[params.links]]
	iconset = "fas"
        icon = "pound-sign"
        title = "Cash App"
        url = "https://cash.app/%C2%A3StableStool"  
	
    [[params.links]]
	iconset = "fab"
        icon = "patreon"
        title = "Patreon"
        url = "https://www.patreon.com/VeryStableMilkingStool?fan_landing=true"    

    [[params.links]]
        icon = "amazon"
        title = "Amazon"
        url = "https://www.amazon.co.uk/hz/wishlist/ls/3HY734U4GTMET?ref_=wl_share"
    
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/CiderGuru/"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:stool@stablemilkingstool.co.uk"



      